balises_qgis <-
function(){
  canevas <- data.frame(V1=c('<!DOCTYPE qgis PUBLIC "http://mrcc.com/qgis.dtd" "SYSTEM">',
                                  paste0('<qgis projectname="" version="3.10.12-A Coru','\u00F1','a">'),
                                  '<title></title>',
                                  '<mapcanvas>',
                                  '<units>meters</units>',
                                  '<extent>',
                                  '<xmin>XXXMIN</xmin>',
                                  '<ymin>YYYMIN</ymin>',
                                  '<xmax>XXXMAX</xmax>',
                                  '<ymax>YYYMAX</ymax>',
                                  '</extent>',
                                  '<projections>0</projections>',
                                  '\t\t<destinationsrs>',
                                  '<spatialrefsys>',
                                  '<proj4>PROJECTIONPROJET</proj4>',
                                  '</spatialrefsys>',
                                  '</destinationsrs>',
                                  '</mapcanvas>',
                                  '<legend updateDrawingOrder="false">',
                                  'BLOCLEGENDE',
                                  '</legend>',
                                  'BLOCCOMPOSER',
                                  '<projectlayers layercount="NOMBREDEFONDS">',
                                  'BLOCPROJECTLAYERS',
                                  '</projectlayers>',
                                  '</qgis>'))
  
  canevas_MEP <- data.frame(V1=c('<Composer title="MEP_NOMMEP" visible="1">',
                                      '<Composition printResolution="300" paperWidth="297" snapGridOffsetX="0" snapGridResolution="10" snapGridOffsetY="0" alignmentSnap="1" snapping="0" numPages="1" paperHeight="210" alignmentSnapTolerance="2" printAsRaster="0">',
                                      '<ComposerLabel valign="32" marginX="0" marginY="0" labelText="SSTIT" htmlState="0" halign="1">',
                                      '<LabelFont description="Arial 2,10,-1,5,50,0,0,0,0,0"/>',
                                      '<FontColor red="0" blue="0" green="0"/>',
                                      '<ComposerItem width="277" x="10" transparency="0" y="17" rotation="0" height="10.2606" positionMode="0" frame="false" outlineWidth="0.3" zValue="5" lastValidViewScaleFactor="3.36577" uuid="{18497c73-469f-4b55-a8e2-7f6d121e3d5c}" id="" background="false" blendMode="0" positionLock="false">',
                                      '<FrameColor alpha="255" red="0" blue="0" green="0"/>',
                                      '<BackgroundColor alpha="255" red="255" blue="255" green="255"/>',
                                      '</ComposerItem>',
                                      '</ComposerLabel>',
                                      '<ComposerLabel valign="32" marginX="0" marginY="0" labelText="copyright IGN-Insee AN" htmlState="0" htmlState="0" halign="4">',
                                      '<LabelFont description="Arial 2,10,-1,5,50,0,0,0,0,0"/>',
                                      '<FontColor red="0" blue="0" green="0"/>',
                                      '<ComposerItem pagey="102.681" page="1" id="" lastValidViewScaleFactor="-1" positionMode="3" positionLock="false" x="287" y="102.681" visibility="1" zValue="4" background="true" transparency="0" frameJoinStyle="miter" blendMode="0" width="45" outlineWidth="0.3" excludeFromExports="0" uuid="{c289f7e3-3867-4604-b919-f0424952ab2b}" height="6" itemRotation="90" frame="false" pagex="287">',
                                      '<FrameColor alpha="255" red="0" blue="0" green="0"/>',
                                      '<BackgroundColor alpha="255" red="255" blue="255" green="255"/>',
                                      '</ComposerItem>',
                                      '</ComposerLabel>',
                                      '<ComposerLabel valign="32" marginX="0" marginY="0" labelText="SOURCE" htmlState="0" halign="4">',
                                      '<LabelFont description="Arial 2,10,-1,5,50,0,0,0,0,0"/>',
                                      '<FontColor red="0" blue="0" green="0"/>',
                                      '<ComposerItem pagey="195.819" page="1" id="" lastValidViewScaleFactor="2.29858" positionMode="6" positionLock="false" x="10" y="195.819" visibility="1" zValue="3" background="false" transparency="0" frameJoinStyle="miter" blendMode="0" width="277" outlineWidth="0.3" excludeFromExports="0" uuid="{a3245887-fd21-4ce7-a608-b41ca3448592}" height="4.181" itemRotation="0" frame="false" pagex="10">',
                                      '<FrameColor alpha="255" red="0" blue="0" green="0"/>',
                                      '<BackgroundColor alpha="255" red="255" blue="255" green="255"/>',
                                      '</ComposerItem>',
                                      '</ComposerLabel>',
                                      '<ComposerLabel valign="32" labelText="TITRE" htmlState="0" halign="0" margin="0">',
                                      '<LabelFont description="Arial 2,14,-1,5,75,0,0,0,0,0"/>',
                                      '<FontColor red="0" blue="0" green="0"/>',
                                      '<ComposerItem width="277" x="10" transparency="0" y="10" rotation="0" height="9.97584" positionMode="0" frame="false" outlineWidth="0.3" zValue="6" lastValidViewScaleFactor="3.36577" uuid="{4e213bc9-08e0-4e1e-b1c0-a67086fc5d57}" id="" background="false" blendMode="0" positionLock="false">',
                                      '<FrameColor alpha="255" red="0" blue="0" green="0"/>',
                                      '<BackgroundColor alpha="255" red="255" blue="255" green="255"/>',
                                      '</ComposerItem>',
                                      '</ComposerLabel>',
                                      '<ComposerLegend symbolWidth="4" title="" boxSpace="2" splitLayer="0" equalColumnWidth="0" map="0" symbolHeight="4" wrapChar="" fontColor="#000000" columnSpace="2" columnCount="1">',
                                      '<styles>',
                                      '<style marginBottom="2" name="title" font="Arial 2,16,-1,5,50,0,0,0,0,0"/>',
                                      '<style marginTop="2" name="group" font="Arial 2,14,-1,5,50,0,0,0,0,0"/>',
                                      '<style marginTop="2" name="subgroup" font="Arial 2,12,-1,5,50,0,0,0,0,0"/>',
                                      '<style marginTop="2" name="symbol" font="Arial 2,8.25,-1,5,50,0,0,0,0,0"/>',
                                      '<style marginTop="2" marginLeft="2" name="symbolLabel" font="Arial 2,12,-1,5,50,0,0,0,0,0"/>',
                                      '</styles>',
                                      '<Model autoUpdate="1">',
                                      'BLOCLAYERITEM',
                                      '</Model>',
                                      '<ComposerItem width="60.6" x="12" transparency="0" y="130" rotation="0" height="63.4" positionMode="0" frame="false" outlineWidth="0.3" zValue="2" lastValidViewScaleFactor="3.36577" uuid="{7a2b6e79-76cb-4933-8068-9058342234a6}" id="" background="true" blendMode="0" positionLock="false">',
                                      '<FrameColor alpha="255" red="0" blue="0" green="0"/>',
                                      '<BackgroundColor alpha="255" red="255" blue="255" green="255"/>',
                                      '</ComposerItem>',
                                      '</ComposerLegend>',
                                      '<ComposerMap keepLayerSet="false" overviewFrameMap="-1" id="0" previewMode="Cache" drawCanvasItems="true">',
                                      '<overviewFrame overviewBlendMode="0" overviewFrameMap="-1" overviewInverted="false">',
                                      '<symbol alpha="0.3" type="fill" name="">',
                                      '<layer pass="0" class="SimpleFill" locked="0">',
                                      '<prop k="border_width_unit" v="MM"/>',
                                      '<prop k="color" v="255,0,0,255"/>',
                                      '<prop k="color_border" v="0,0,0,255"/>',
                                      '<prop k="offset" v="0,0"/>',
                                      '<prop k="offset_unit" v="MM"/>',
                                      '<prop k="style" v="solid"/>',
                                      '<prop k="style_border" v="no"/>',
                                      '<prop k="width_border" v="0.26"/>',
                                      '</layer>',
                                      '</symbol>',
                                      '</overviewFrame>',
                                      '<Extent ymin="YYYMIN" xmin="XXXMIN" ymax="YYYMAX" xmax="XXXMAX"/>',
                                      '<LayerSet/>',
                                      '<Grid gridStyle="0" crossLength="3" intervalX="0" offsetX="0" intervalY="0" offsetY="0" gridFrameStyle="0" gridFrameWidth="2" gridBlendMode="0" show="0">',
                                      '<symbol alpha="1" type="line" name="">',
                                      '<layer pass="0" class="SimpleLine" locked="0">',
                                      '<prop k="capstyle" v="flat"/>',
                                      '<prop k="color" v="0,0,0,255"/>',
                                      '<prop k="customdash" v="5;2"/>',
                                      '<prop k="customdash_unit" v="MM"/>',
                                      '<prop k="joinstyle" v="bevel"/>',
                                      '<prop k="offset" v="0"/>',
                                      '<prop k="offset_unit" v="MM"/>',
                                      '<prop k="penstyle" v="solid"/>',
                                      '<prop k="use_custom_dash" v="0"/>',
                                      '<prop k="width" v="0.3"/>',
                                      '<prop k="width_unit" v="MM"/>',
                                      '</layer>',
                                      '</symbol>',
                                      '<Annotation rightDirection="0" bottomDirection="0" format="0" topPosition="1" precision="3" leftDirection="0" rightPosition="1" bottomPosition="1" frameDistance="1" show="0" font="Arial 2,8.25,-1,5,50,0,0,0,0,0" leftPosition="1" topDirection="0">',
                                      '<fontColor red="0" blue="0" green="0"/>',
                                      '</Annotation>',
                                      '</Grid>',
                                      '<ComposerItem width="277" x="10" transparency="0" y="22" rotation="0" height="168" positionMode="0" frame="false" outlineWidth="0.3" zValue="1" lastValidViewScaleFactor="3.36577" uuid="{1aac5ac9-b6b7-4dfd-a5e7-383ac82c2309}" id="" background="true" blendMode="0" positionLock="false">',
                                      '<FrameColor alpha="255" red="0" blue="0" green="0"/>',
                                      '<BackgroundColor alpha="255" red="255" blue="255" green="255"/>',
                                      '</ComposerItem>',
                                      '</ComposerMap>',
                                      '</Composition>',
                                      '</Composer>'))
  
  bloc_leg <- data.frame(V1=c(        '<legendlayer drawingOrder="-1" open="true" checked="Qt::Checked" name="NOMDELACOUCHE" showFeatureCount="0">',
                                      '<filegroup open="true" hidden="false">',
                                      '<legendlayerfile isInOverview="0" layerid="ID_COUCHE" visible="1"/>',
                                      '</filegroup>',
                                      '</legendlayer>'
  ))
  
  blocprojectlayers <- data.frame(V1=c(        '<maplayer minimumScale="0" maximumScale="1e+08" geometry="GEOMETRIE" type="vector" hasScaleBasedVisibilityFlag="0">',
                                               '<id>IDCOUCHE</id>',
                                               '<datasource>CHEMINCOUCHE</datasource>',
                                               '<layername>NOMDELACOUCHE</layername>',
                                               '<srs>',
                                               '<spatialrefsys>',
                                               '<proj4>PROJECTIONDELACOUCHE</proj4>',
                                               '</spatialrefsys>',
                                               '</srs>',
                                               '<transparencyLevelInt>255</transparencyLevelInt>',
                                               '<provider encoding="latin1">ogr</provider>',
                                               '<vectorjoins/>',
                                               '<renderer-v2 ATTR symbollevels="0" type="TYPEANALYSE">',
                                               'BLOCCATEGORIES',
                                               '<symbols>',
                                               'BLOCSYMBOLS',
                                               '</symbols>',
                                               '<rotation field=""/>',
                                               '<sizescale field="" scalemethod="area"/>',
                                               '</renderer-v2>',
                                               '<customproperties/>',
                                               '<displayfield></displayfield>',
                                               '</maplayer>'))
  
  blocsymbolsPolygon <- data.frame(V1=c(                    '<symbol alpha="1" type="fill" name="NAME">',
                                                            '<layer pass="0" class="SimpleFill" locked="0">',
                                                            '<prop k="border_width_unit" v="MM"/>',
                                                            '<prop k="color" v="COULEURFOND"/>',
                                                            '<prop k="color_border" v="COULEURBORDURE"/>',
                                                            '<prop k="offset" v="0,0"/>',
                                                            '<prop k="offset_unit" v="MM"/>',
                                                            '<prop k="style" v="REMPLISSAGEFOND"/>',
                                                            '<prop k="style_border" v="STYLEBORDURE"/>',
                                                            '<prop k="width_border" v="EPAISSEURBORDURE"/>',
                                                            '</layer>',
                                                            '</symbol>'
  ))
  
  blocsymbolsPoint <- data.frame(V1=c(                    '<symbol alpha="1" type="marker" name="0">',
                                                          '<layer pass="0" class="SimpleMarker" locked="0">',
                                                          '<prop k="angle" v="0"/>',
                                                          '<prop k="color" v="0,0,0"/>',
                                                          '<prop k="color_border" v="0,0,0"/>',
                                                          '<prop k="name" v="circle"/>',
                                                          '<prop k="offset" v="0,0"/>',
                                                          '<prop k="offset_unit" v="MM"/>',
                                                          '<prop k="outline_width" v="0"/>',
                                                          '<prop k="outline_width_unit" v="MM"/>',
                                                          '<prop k="scale_method" v="area"/>',
                                                          '<prop k="size" v="2"/>',
                                                          '<prop k="size_unit" v="MM"/>',
                                                          '</layer>',
                                                          '</symbol>'
  ))
  
  blocsymbolsLine <- data.frame(V1=c(                    '<symbol alpha="1" type="line" name="NAME">',
                                                         '<layer pass="0" class="SimpleLine" locked="0">',
                                                         '<prop k="capstyle" v="square"/>',
                                                         '<prop k="color" v="COULEURBORDURE"/>',
                                                         '<prop k="customdash" v="5;2"/>',
                                                         '<prop k="customdash_unit" v="MM"/>',
                                                         '<prop k="joinstyle" v="bevel"/>',
                                                         '<prop k="offset" v="0"/>',
                                                         '<prop k="offset_unit" v="MM"/>',
                                                         '<prop k="penstyle" v="STYLEBORDURE"/>',
                                                         '<prop k="use_custom_dash" v="0"/>',
                                                         '<prop k="width" v="EPAISSEURBORDURE"/>',
                                                         '<prop k="width_unit" v="MM"/>',
                                                         '</layer>',
                                                         '</symbol>'
  ))
  
  bloccategories <- data.frame(V1=c(                    '<category symbol="SYMBOL" value="VALUE" label="LABEL"/>'))
  
  bloclayerItem <- data.frame(V1=c('<LayerItem layerId="ID_COUCHE" userText="NOMDELACOUCHE" style="STYLELEG" text="NOMDELACOUCHE" showFeatureCount="0">',
                                   'BLOCVECTORCLASSIFICATION',
                                   '</LayerItem>'))
  
  blocvectorClassification <- data.frame(V1=c(                        '<VectorClassificationItemNg userText="" text="TEXT">',
                                                                      '<symbols>',
                                                                      'BLOCSYMBOLS',
                                                                      '</symbols>',
                                                                      '</VectorClassificationItemNg>'))
  
  blocgenerator <- data.frame(V1=c(                '<layer locked="0" pass="0" enabled="1" class="GeometryGenerator">',
                                                   '<prop k="SymbolType" v="Line"/>',
                                                   '<prop k="geometryModifier" v=" make_line(make_point(x($geometry),y_max($geometry)), make_point(x($geometry)+maximum(bounds_width($geometry))/1.8,y_max($geometry)))"/>',
                                                   '<data_defined_properties>',
                                                   '<Option type="Map">',
                                                   '<Option type="QString" name="name" value=""/>',
                                                   '<Option name="properties"/>',
                                                   '<Option type="QString" name="type" value="collection"/>',
                                                   '</Option>',
                                                   '</data_defined_properties>',
                                                   '<symbol type="line" alpha="1" name="@0@1" force_rhr="0" clip_to_extent="1">',
                                                   '<layer locked="0" pass="0" enabled="1" class="SimpleLine">',
                                                   '<prop k="capstyle" v="square"/>',
                                                   '<prop k="customdash" v="5;2"/>',
                                                   '<prop k="customdash_map_unit_scale" v="3x:0,0,0,0,0,0"/>',
                                                   '<prop k="customdash_unit" v="MM"/>',
                                                   '<prop k="draw_inside_polygon" v="0"/>',
                                                   '<prop k="joinstyle" v="bevel"/>',
                                                   '<prop k="line_color" v="0,0,0,255"/>',
                                                   '<prop k="line_style" v="solid"/>',
                                                   '<prop k="line_width" v="0.1"/>',
                                                   '<prop k="line_width_unit" v="MM"/>',
                                                   '<prop k="offset" v="0"/>',
                                                   '<prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>',
                                                   '<prop k="offset_unit" v="MM"/>',
                                                   '<prop k="ring_filter" v="0"/>',
                                                   '<prop k="use_custom_dash" v="0"/>',
                                                   '<prop k="width_map_unit_scale" v="3x:0,0,0,0,0,0"/>',
                                                   '<data_defined_properties>',
                                                   '<Option type="Map">',
                                                   '<Option type="QString" name="name" value=""/>',
                                                   '<Option name="properties"/>',
                                                   '<Option type="QString" name="type" value="collection"/>',
                                                   '</Option>',
                                                   '</data_defined_properties>',
                                                   '</layer>',
                                                   '</symbol>',
                                                   '</layer>'))
  
  bloclabeling <- data.frame(V1=c(        '<labeling type="simple">',
                                          '<settings calloutType="simple">',
                                          '<text-style fontWordSpacing="0" fontItalic="0" fontCapitals="0" blendMode="0" fieldName="replace(lpad(format_number( &quot;ETI_VAL&quot; ,0,\'DE\'),&#xd;&#xa;max_length(format_number( &quot;ETI_VAL&quot; ,0))+1,&#xd;&#xa;\' \'),\'.\', \' \')&#xa;" textColor="0,0,0,255" fontSizeMapUnitScale="3x:0,0,0,0,0,0" textOrientation="horizontal" textOpacity="1" namedStyle="Regular" fontWeight="50" previewBkgrdColor="255,255,255,255" fontKerning="0" fontLetterSpacing="0" isExpression="1" useSubstitutions="0" multilineHeight="1" fontSizeUnit="Point" fontStrikeout="0" fontUnderline="0" fontSize="8">',
                                          '<text-buffer bufferDraw="0" bufferSize="1" bufferJoinStyle="128" bufferColor="255,255,255,255" bufferBlendMode="0" bufferSizeUnits="MM" bufferOpacity="1" bufferSizeMapUnitScale="3x:0,0,0,0,0,0" bufferNoFill="1"/>',
                                          '<background shapeRadiiY="0" shapeOffsetMapUnitScale="3x:0,0,0,0,0,0" shapeOpacity="1" shapeOffsetUnit="MM" shapeRadiiUnit="MM" shapeFillColor="255,255,255,255" shapeBorderWidthUnit="MM" shapeRadiiX="0" shapeSizeY="0" shapeSizeType="0" shapeBlendMode="0" shapeSizeX="0" shapeSVGFile="" shapeBorderWidthMapUnitScale="3x:0,0,0,0,0,0" shapeDraw="0" shapeOffsetX="0" shapeRadiiMapUnitScale="3x:0,0,0,0,0,0" shapeRotationType="0" shapeBorderColor="128,128,128,255" shapeBorderWidth="0" shapeSizeUnit="MM" shapeJoinStyle="64" shapeSizeMapUnitScale="3x:0,0,0,0,0,0" shapeType="0" shapeRotation="0" shapeOffsetY="0">',
                                          '<symbol type="marker" alpha="1" name="markerSymbol" force_rhr="0" clip_to_extent="1">',
                                          '<layer locked="0" pass="0" enabled="1" class="SimpleMarker">',
                                          '<prop k="angle" v="0"/>',
                                          '<prop k="color" v="255,158,23,255"/>',
                                          '<prop k="horizontal_anchor_point" v="1"/>',
                                          '<prop k="joinstyle" v="bevel"/>',
                                          '<prop k="name" v="circle"/>',
                                          '<prop k="offset" v="0,0"/>',
                                          '<prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>',
                                          '<prop k="offset_unit" v="MM"/>',
                                          '<prop k="outline_color" v="35,35,35,255"/>',
                                          '<prop k="outline_style" v="solid"/>',
                                          '<prop k="outline_width" v="0"/>',
                                          '<prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>',
                                          '<prop k="outline_width_unit" v="MM"/>',
                                          '<prop k="scale_method" v="diameter"/>',
                                          '<prop k="size" v="2"/>',
                                          '<prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>',
                                          '<prop k="size_unit" v="MM"/>',
                                          '<prop k="vertical_anchor_point" v="1"/>',
                                          '<data_defined_properties>',
                                          '<Option type="Map">',
                                          '<Option type="QString" name="name" value=""/>',
                                          '<Option name="properties"/>',
                                          '<Option type="QString" name="type" value="collection"/>',
                                          '</Option>',
                                          '</data_defined_properties>',
                                          '</layer>',
                                          '</symbol>',
                                          '</background>',
                                          '<shadow shadowUnder="0" shadowOffsetMapUnitScale="3x:0,0,0,0,0,0" shadowOffsetGlobal="1" shadowColor="0,0,0,255" shadowDraw="0" shadowRadius="1.5" shadowRadiusMapUnitScale="3x:0,0,0,0,0,0" shadowOpacity="0.7" shadowRadiusAlphaOnly="0" shadowOffsetUnit="MM" shadowOffsetDist="1" shadowOffsetAngle="135" shadowRadiusUnit="MM" shadowBlendMode="6" shadowScale="100"/>',
                                          '<dd_properties>',
                                          '<Option type="Map">',
                                          '<Option type="QString" name="name" value=""/>',
                                          '<Option name="properties"/>',
                                          '<Option type="QString" name="type" value="collection"/>',
                                          '</Option>',
                                          '</dd_properties>',
                                          '<substitutions/>',
                                          '</text-style>',
                                          '<text-format addDirectionSymbol="0" wrapChar="" reverseDirectionSymbol="0" autoWrapLength="0" plussign="0" placeDirectionSymbol="0" decimals="3" useMaxLineLengthForAutoWrap="1" multilineAlign="0" leftDirectionSymbol="&lt;" rightDirectionSymbol=">" formatNumbers="0"/>',
      '<placement overrunDistanceUnit="MM" dist="0" geometryGeneratorType="PointGeometry" layerType="PolygonGeometry" geometryGeneratorEnabled="0" distUnits="MM" centroidWhole="1" offsetUnits="MM" predefinedPositionOrder="TR,TL,BR,BL,R,L,TSR,BSR" geometryGenerator="" maxCurvedCharAngleOut="-25" overrunDistance="0" rotationAngle="0" fitInPolygonOnly="0" quadOffset="5" maxCurvedCharAngleIn="25" repeatDistance="0" distMapUnitScale="3x:0,0,0,0,0,0" repeatDistanceUnits="MM" priority="5" yOffset="0" centroidInside="0" placementFlags="10" preserveRotation="1" repeatDistanceMapUnitScale="3x:0,0,0,0,0,0" placement="1" overrunDistanceMapUnitScale="3x:0,0,0,0,0,0" offsetType="0" labelOffsetMapUnitScale="3x:0,0,0,0,0,0" xOffset="0"/>',
      '<rendering scaleMax="0" minFeatureSize="0" displayAll="1" labelPerPart="0" zIndex="0" limitNumLabels="0" scaleVisibility="0" fontLimitPixelSize="0" obstacle="1" drawLabels="1" mergeLines="0" scaleMin="0" fontMaxPixelSize="10000" maxNumLabels="2000" obstacleFactor="1" obstacleType="0" fontMinPixelSize="3" upsidedownLabels="0"/>',
      '<dd_properties>',
        '<Option type="Map">',
          '<Option type="QString" name="name" value=""/>',
          '<Option type="Map" name="properties">',
            '<Option type="Map" name="PositionX">',
              '<Option type="bool" name="active" value="true"/>',
              '<Option type="QString" name="expression" value="x( $geometry ) +  maximum(bounds_width($geometry))/1.8"/>',
              '<Option type="int" name="type" value="3"/>',
            '</Option>',
            '<Option type="Map" name="PositionY">',
              '<Option type="bool" name="active" value="true"/>',
              '<Option type="QString" name="expression" value="y_max($geometry)"/>',
              '<Option type="int" name="type" value="3"/>',
            '</Option>',
            '<Option type="Map" name="Vali">',
              '<Option type="bool" name="active" value="true"/>',
              '<Option type="QString" name="expression" value="\'Half\'"/>',
              '<Option type="int" name="type" value="3"/>',
            '</Option>',
          '</Option>',
          '<Option type="QString" name="type" value="collection"/>',
        '</Option>',
      '</dd_properties>',
      '<callout type="simple">',
        '<Option type="Map">',
          '<Option type="QString" name="anchorPoint" value="pole_of_inaccessibility"/>',
          '<Option type="Map" name="ddProperties">',
            '<Option type="QString" name="name" value=""/>',
            '<Option name="properties"/>',
            '<Option type="QString" name="type" value="collection"/>',
          '</Option>',
          '<Option type="bool" name="drawToAllParts" value="false"/>',
          '<Option type="QString" name="enabled" value="0"/>',
          '<Option type="QString" name="lineSymbol" value="&lt;symbol type=&quot;line&quot; alpha=&quot;1&quot; name=&quot;symbol&quot; force_rhr=&quot;0&quot; clip_to_extent=&quot;1&quot;>&lt;layer locked=&quot;0&quot; pass=&quot;0&quot; enabled=&quot;1&quot; class=&quot;SimpleLine&quot;>&lt;prop k=&quot;capstyle&quot; v=&quot;square&quot;/>&lt;prop k=&quot;customdash&quot; v=&quot;5;2&quot;/>&lt;prop k=&quot;customdash_map_unit_scale&quot; v=&quot;3x:0,0,0,0,0,0&quot;/>&lt;prop k=&quot;customdash_unit&quot; v=&quot;MM&quot;/>&lt;prop k=&quot;draw_inside_polygon&quot; v=&quot;0&quot;/>&lt;prop k=&quot;joinstyle&quot; v=&quot;bevel&quot;/>&lt;prop k=&quot;line_color&quot; v=&quot;60,60,60,255&quot;/>&lt;prop k=&quot;line_style&quot; v=&quot;solid&quot;/>&lt;prop k=&quot;line_width&quot; v=&quot;0.3&quot;/>&lt;prop k=&quot;line_width_unit&quot; v=&quot;MM&quot;/>&lt;prop k=&quot;offset&quot; v=&quot;0&quot;/>&lt;prop k=&quot;offset_map_unit_scale&quot; v=&quot;3x:0,0,0,0,0,0&quot;/>&lt;prop k=&quot;offset_unit&quot; v=&quot;MM&quot;/>&lt;prop k=&quot;ring_filter&quot; v=&quot;0&quot;/>&lt;prop k=&quot;use_custom_dash&quot; v=&quot;0&quot;/>&lt;prop k=&quot;width_map_unit_scale&quot; v=&quot;3x:0,0,0,0,0,0&quot;/>&lt;data_defined_properties>&lt;Option type=&quot;Map&quot;>&lt;Option type=&quot;QString&quot; name=&quot;name&quot; value=&quot;&quot;/>&lt;Option name=&quot;properties&quot;/>&lt;Option type=&quot;QString&quot; name=&quot;type&quot; value=&quot;collection&quot;/>&lt;/Option>&lt;/data_defined_properties>&lt;/layer>&lt;/symbol>"/>',
                                          '<Option type="double" name="minLength" value="0"/>',
                                          '<Option type="QString" name="minLengthMapUnitScale" value="3x:0,0,0,0,0,0"/>',
                                          '<Option type="QString" name="minLengthUnit" value="MM"/>',
                                          '<Option type="double" name="offsetFromAnchor" value="0"/>',
                                          '<Option type="QString" name="offsetFromAnchorMapUnitScale" value="3x:0,0,0,0,0,0"/>',
                                          '<Option type="QString" name="offsetFromAnchorUnit" value="MM"/>',
                                          '<Option type="double" name="offsetFromLabel" value="0"/>',
                                          '<Option type="QString" name="offsetFromLabelMapUnitScale" value="3x:0,0,0,0,0,0"/>',
                                          '<Option type="QString" name="offsetFromLabelUnit" value="MM"/>',
                                          '</Option>',
                                          '</callout>',
                                          '</settings>',
                                          '</labeling>'))
  
  blocproperties <- data.frame(V1=c( 	'<properties>',
                                      '<PositionPrecision>',
                                      '<Automatic type="bool">true</Automatic>',
                                      '<DecimalPlaces type="int">2</DecimalPlaces>',
                                      '</PositionPrecision>',
                                      '<PAL>',
                                      '<ShowingCandidates type="bool">false</ShowingCandidates>',
                                      '<TextFormat type="int">0</TextFormat>',
                                      '<CandidatesPoint type="int">16</CandidatesPoint>',
                                      '<SearchMethod type="int">0</SearchMethod>',
                                      '<CandidatesPolygon type="int">30</CandidatesPolygon>',
                                      '<ShowingPartialsLabels type="bool">true</ShowingPartialsLabels>',
                                      '<CandidatesLine type="int">50</CandidatesLine>',
                                      '<DrawRectOnly type="bool">false</DrawRectOnly>',
                                      '<ShowingAllLabels type="bool">false</ShowingAllLabels>',
                                      '</PAL>',
                                      '<Paths>',
                                      '<Absolute type="bool">false</Absolute>',
                                      '</Paths>',
                                      '<Legend>',
                                      '<filterByMap type="bool">false</filterByMap>',
                                      '</Legend>',
                                      '<Measurement>',
                                      '<DistanceUnits type="QString">','</DistanceUnits>',
                                      '<AreaUnits type="QString">','</AreaUnits>',
                                      '</Measurement>',
                                      '<Measure>',
                                      '<Ellipsoid type="QString">WGS84</Ellipsoid>',
                                      '</Measure>',
                                      '<SpatialRefSys>',
                                      '<ProjectionsEnabled type="int">1</ProjectionsEnabled>',
                                      '</SpatialRefSys>',
                                      '<Gui>',
                                      '<SelectionColorAlphaPart type="int">255</SelectionColorAlphaPart>',
                                      '<CanvasColorRedPart type="int">255</CanvasColorRedPart>',
                                      '<SelectionColorRedPart type="int">255</SelectionColorRedPart>',
                                      '<CanvasColorBluePart type="int">255</CanvasColorBluePart>',
                                      '<SelectionColorGreenPart type="int">255</SelectionColorGreenPart>',
                                      '<SelectionColorBluePart type="int">0</SelectionColorBluePart>',
                                      '<CanvasColorGreenPart type="int">255</CanvasColorGreenPart>',
                                      '</Gui>',
                                      '</properties>'))
  
  return(list(canevas,canevas_MEP,bloc_leg,blocprojectlayers,blocsymbolsPolygon,blocsymbolsPoint,blocsymbolsLine,bloccategories,bloclayerItem,blocvectorClassification,blocgenerator,bloclabeling,blocproperties))
}
