name: R

on:
  push:
    branches:
      - version_1.8.3
  pull_request:
    branches:
      - version_1.8.3

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: [3.3, 3.6, 4.0, 4.1]
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install Depends
        run: install.packages(c("shiny", "shinyBS"))
      - name: Install Imports
        run: install.packages(c("sf", "utils", "shinyjs", "shinythemes", "DT", "stringr", "leaflet", "leaflet.extras", "classInt" , "grDevices", "ggplot2", "dplyr", "graphics", "lwgeom", "mapview", "zip"))
      - name: Install Suggests
        run: install.packages(c("knitr", "rmarkdown", "markdown", "rio"))
      - name: Check
        run: |
          install.package("rcmdcheck")
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
