name: R

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: [3.6, 4.0, 4.1, 4.2]
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install libraries Debian
        run: |
          sudo apt-get install -y libudunits2-dev
          sudo apt-get install -y libgdal-dev
          sudo apt-get install -y qpdf
          sudo apt-get install -y curl
          sudo apt-get install -y pandoc
          sudo apt-get install -y texlive-latex-base
          sudo apt-get install -y texlive-latex-recommended
          sudo apt-get install -y texlive-latex-extra
          sudo apt-get install -y texlive-extra-utils
          sudo apt-get install -y libmagick++-dev
          sudo apt-get install -y cargo
          sudo apt-get install -y lmodern
          sudo apt-get install -y libharfbuzz-dev
          sudo apt-get install -y libfribidi-dev
      - name: Install Depends
        run: install.packages(c("shiny", "shinyBS"))
        shell: Rscript {0}
      - name: Install Imports
        run: install.packages(c("classInt" , "sf", "shinyjs", "shinythemes", "DT", "stringr", "leaflet", "leaflet.extras", "ggplot2", "dplyr", "lwgeom", "mapview", "zip"))
        shell: Rscript {0}
      - name: Install Suggests
        run: install.packages(c("knitr", "rmarkdown", "markdown", "rio"))
        shell: Rscript {0}
      - name: Check
        run: |
          install.packages("rcmdcheck")
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}